In [1]:
import pandas as pd

# 1. Cargamos el archivo
df = pd.read_csv("convocatorias_sociales_pe.csv", encoding="utf-8")

# 2. Le decimos a Pandas que no corte el texto largo en las columnas
pd.set_option('display.max_colwidth', None)

# 3. Mostramos las primeras 50 filas de la columna 'description' como Data Frame
df[['description']].head(50)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         description
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Estoy en búsqueda de Sociólogo o Especialista en Asuntos Sociales que brinde capacitaciones en Piura, con experiencia en gestión social minera, formulación y gestión de proyectos de desarrollo comunitario.\n\n**Requisitos:**\n\n* Titulado\n* Experiencia en manejo de grupo\n* Experiencia capacitando\n* Residir en Piura\n\nEnviar currículum a: seleccion.empresarial@cdh\-peru.com  \nO al: \+51 977538263\n\nLugar de trabajo: Empleo presencial
1   **Somos una compañía internacional formada por más de 65\.000 empleados y presente en más de 40 países de los cinco continentes. Líderes en innovación y desarrollo tecnológico, buscamos expertos en impulsar el desarrollo sostenible y encontrar soluciones a los mayores retos mundiales, como el calentamiento global, la superpoblación y la escasez hídrica.**\n\n**Descripción del puesto**\n\n**Misión:**\n\n\nRealizar el seguimiento, supervisión y control de la gestión predial de los proyectos a su cargo, asegurando el cumplimiento de los objetivos de plazo, costo, calidad y gestión social, mediante la coordinación con consultoras externas, autoridades y grupos de interés, contribuyendo al desarrollo oportuno y sostenible de los proyectos.\n\n**Requisitos del candidato**\n\n**Acciona Transmisión Perú S.A.,** se encuentra en la búsqueda de un(a) Analista Predial que contribuya en la gestión predial de nuestros proyectos de transmisión eléctrica, asegurando el cumplimiento de los plazos y estándares de calidad de la organización, con capacidad de organización, seguimiento y coordinación, interesados en desarrollar su experiencia en proyectos de infraestructura y gestión territorial.\n\n**Funciones:**\n\n* Encargarse de la supervisión y monitoreo de la gestión predial del proyecto en el que participa.\n* Realizar el seguimiento a las actividades de gestión predial ejecutadas por la consultora.\n* cargo del proyecto velando por el cumplimiento de los objetivos de plazo y costo.\n* Supervisar el avance y cumplimiento de las actividades realizadas por las consultoras externas, asegurando calidad, plazos y presupuesto\n* Participar en procesos de negociación predial y reuniones con diversos actores.\n* Contribuir al desarrollo e implementación de la estrategia de gestión social – predial del proyecto en colaboración con el coordinador de sostenibilidad.\n* Participar en reuniones de seguimiento estratégicas de la gestión de permisos de los proyectos en los que participa.\n* Elaborar reportes diarios, semanales y mensuales de avance predial, usando herramientas\n* avanzadas de análisis y visualización (Excel, Power BI).\n* Diseñar, revisar procesos internos de la gestión predial (flujos, formatos, matrices)\n* Generar mapas, polígonos, capas temáticas y análisis espaciales para decisiones de la gerencia.\n* Reportar los avances de la gestión predial de los proyectos en los que participa.\n* Identificar, analizar y reportar riesgos e incidencias asociados a la gestión predial, proponiendo medidas de mitigación y planes de acción oportunos.\n* Realizar el seguimiento al cumplimiento de los compromisos asumidos con propietarios, comunidades, autoridades y demás grupos de interés vinculados a la gestión predial.\n* Administrar y mantener actualizada la información predial y documental de los proyectos,\n* asegurando la trazabilidad y disponibilidad de la información.\n* Coordinar con las áreas técnicas, legales, ambientales y de sostenibilidad para garantizar la adecuada ejecución de la gestión predial del proyecto.\n* Elaborar indicadores de gestión (KPI) y cuadros de control que permitan monitorear el desempeño y avance de la gestión predial.\n* Apoyar en la elaboración de presupuestos, cronogramas y proyecciones relacionados con la gestión predial de los proyectos.\n* Demás funciones asignadas por el jefe directo.\n\n**Perfil**\n\n**Formación académica / Titulación:**\n\n* Derecho, antropología, sociología, ingeniería industrial, ingeniería geógrafa o carreras afines relacionadas con la gestión territorial, social y predial.\n* Se valorarán estudios de especialización o diplomados en gestión predial, gestión social, catastro, SIG o gestión de proyectos.\n\n**Experiencia:**\n\n* Es necesaria la experiencia mínima de 4 años en la gestión predial de proyectos lineales.\n* Experiencia en procesos de negociación, saneamiento físico\-legal, servidumbres y relacionamiento con propietarios y grupos de interés.\n* Experiencia en supervisión y seguimiento de consultoras externas y contratistas.\n* Se valorará experiencia en proyectos de infraestructura energética, especialmente líneas de transmisión y subestaciones eléctricas.\n\n**Idiomas y nivel requerido**\n\n* Nivel alto de español.\n* Nivel intermedio\-avanzado de inglés (mínimo B2\), deseable para la elaboración y revisión de documentación técnica y coordinación con equipos internacionales.\n\n**Conocimientos complementarios**\n\n* Dominio avanzado de Excel (tablas dinámicas, dashboards).\n* Manejo de Power BI para reportes dinámicos, tableros ejecutivos y análisis predial.\n* Manejo de QGIS y/o Autocad y/o ArcGis para elaboración de mapas y análisis espacial.\n* Conocimiento de normativa predial, servidumbres, adquisición de derechos superficiales y permisos aplicables a proyectos de infraestructura.\n* Conocimiento en interpretación de planos, cartografía y sistemas de información geográfica (SIG).\n* Alto nivel de gestión.\n* Capacidad de análisis, negociación, planificación y resolución de conflictos.\n* Manejo de indicadores (KPI) y herramientas de seguimiento y control de proyectos.\n* Se valorará el conocimiento especifico en proyectos de líneas de transmisión.\n\n**Disponibilidad para viajar** – SI\n\n* Disponibilidad para realizar viajes frecuentes a campo y supervisar actividades prediales en las zonas de influencia de los proyectos.\n\n\nACCIONA ha recibido la certificación Top Employer 2024 y 2025\. Este sello reconoce a la Compañía como una de las mejores empresas para trabajar por su compromiso en situar la gestión de las personas como eje central de su estrategia. Somos una compañía con igualdad de oportunidades y estamos comprometidos con la diversidad. ACCIONA está alineada con la ley Nº 27278 y prohíbe la discriminación basada en el género, raza, religión o idioma.

In [3]:

# Leemos el CSV forzando la codificación utf-8
df = pd.read_csv("convocatorias_sociales_pe.csv", encoding="utf-8")

# Mostramos las primeras filas para comprobar que las tildes y eñes se ven perfectas
display(df.head(50))

,id,site,job_url,job_url_direct,title,company,location,date_posted,job_type,salary_source,...,company_num_employees,company_revenue,company_description,skills,experience_range,company_rating,company_reviews_count,vacancy_count,work_from_home_type,termino_de_busqueda
0,in-6f9b4a70148f6a96,indeed,https://pe.indeed.com/viewjob?jk=6f9b4a70148f6a96,http://pe.indeed.com/job/soci%C3%B3logo-6f9b4a70148f6a96,Sociólogo,CDH Empresarial,"Piura, PIU, PE",2026-07-28,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sociologia
1,in-c06ca0fc0b2a3d7c,indeed,https://pe.indeed.com/viewjob?jk=c06ca0fc0b2a3d7c,https://acciona.wd3.myworkdayjobs.com/en-US/ACCIONA_Employment_Channel/job/Lima/ANALISTA-PREDIAL_20099440,ANALISTA PREDIAL,Acciona,"Lima, LIM, PE",2026-07-27,NaN,NaN,...,"10,000+",more than $10B (USD),NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sociologia
2,in-5040e485810dd595,indeed,https://pe.indeed.com/viewjob?jk=5040e485810dd595,https://acciona.wd3.myworkdayjobs.com/en-US/ACCIONA_Employment_Channel/job/Lima/ASISTENTE-PREDIAL_20099514,ASISTENTE PREDIAL,Acciona,"Lima, LIM, PE",2026-07-27,NaN,NaN,...,"10,000+",more than $10B (USD),NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sociologia
3,in-30c6bea2e225e1c2,indeed,https://pe.indeed.com/viewjob?jk=30c6bea2e225e1c2,https://oportunidadesalicorp.com/job/Lima-SERVICE-DESIGNER-LIMA/1412609800/,SERVICE DESIGNER,AliCorp,"Lima, LIM, PE",2026-07-25,NaN,NaN,...,"1,001 to 5,000",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sociologia
4,in-cef67bc069fd8396,indeed,https://pe.indeed.com/viewjob?jk=cef67bc069fd8396,https://golder.taleo.net/careersection/globalcareersection/jobdetail.ftl?job=26001023&tz=GMT-05%3A00&tzname=America%2FChicago,Especialista Social Intermedio - Minería,Golder Associates,"Lima, LIM, PE",2026-07-24,fulltime,NaN,...,"5,001 to 10,000",$500M to $1B (USD),NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sociologia
5,in-db49d0e47bd2e5df,indeed,https://pe.indeed.com/viewjob?jk=db49d0e47bd2e5df,http://pe.indeed.com/job/practicante-de-asuntos-p%C3%BAblicos-db49d0e47bd2e5df,Practicante de Asuntos Públicos,Apoyo Comunicación S.A.C.,"San Isidro, LIM, PE",2026-07-24,internship,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sociologia
6,in-8e15d89de8ad7280,indeed,https://pe.indeed.com/viewjob?jk=8e15d89de8ad7280,https://jobs.engie.com/default/job/COORDINADORA-SOCIAL/69339-en_US,COORDINADOR/A SOCIAL,ENGIE,"Chorrillos, LIM, PE",2026-07-22,NaN,NaN,...,"10,000+",more than $10B (USD),NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sociologia
7,in-bbb01d499f332cd7,indeed,https://pe.indeed.com/viewjob?jk=bbb01d499f332cd7,https://camposol.our-jobs.com/job/q5ivl0y7o8,Analista de Sostenibilidad H/F,Camposol S.A,"Chao, LLI, PE",2026-07-22,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sociologia
8,in-19e2df9bb91b5142,indeed,https://pe.indeed.com/viewjob?jk=19e2df9bb91b5142,https://aldesaconstrucciones.factorialhr.com/job_posting/asistente-social-comunitario-tacna-313981?utm_source=indeed,Asistente Social Comunitario - Tacna,GRUPO ALDESA,"San Pedro de Tacna, TAC, PE",2026-07-21,fulltime,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sociologia
9,in-234244862e187d2d,indeed,https://pe.indeed.com/viewjob?jk=234244862e187d2d,https://aldesaconstrucciones.factorialhr.com/job_posting/asistente-social-comunitario-moquegua-313980?utm_source=indeed,Asistente Social Comunitario - Moquegua,GRUPO ALDESA,"Moquegua, MOQ, PE",2026-07-21,fulltime,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sociologia
10,in-90712c7b47d618ce,indeed,https://pe.indeed.com/viewjob?jk=90712c7b47d618ce,http://pe.indeed.com/job/encuestador-90712c7b47d618ce,Encuestador,NaN,"Ilo, MOQ, PE",2026-07-20,fulltime,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sociologia
11,in-ee9cced925aad7ac,indeed,https://pe.indeed.com/viewjob?jk=ee9cced925aad7ac,http://pe.indeed.com/job/especialista-en-impacto-social-y-metodolog%C3%ADa-ee9cced925aad7ac,Especialista en Impacto Social y Metodología,NaN,"Ilo, MOQ, PE",2026-07-20,fulltime,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sociologia
12,in-798a280900fe82f0,indeed,https://pe.indeed.com/viewjob?jk=798a280900fe82f0,http://pe.indeed.com/job/jefe-de-proyecto-coordinador-general-798a280900fe82f0,Jefe de Proyecto / Coordinador General,NaN,"Moquegua, MOQ, PE",2026-07-20,fulltime,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sociologia
13,in-916d61036c67e7a1,indeed,https://pe.indeed.com/viewjob?jk=916d61036c67e7a1,http://pe.indeed.com/job/supervisor-de-campo-916d61036c67e7a1,Supervisor de Campo,NaN,"Moquegua, MOQ, PE",2026-07-20,fulltime,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sociologia
14,in-b70be5327e41794a,indeed,https://pe.indeed.com/viewjob?jk=b70be5327e41794a,http://pe.indeed.com/job/gerente-de-relaciones-p%C3%BAblicas-sector-agroindustrial-b70be5327e41794a,GERENTE DE RELACIONES PÚBLICAS - SECTOR AGROINDUSTRIAL,GRUPO TJC SAC,"Lima, LIM, PE",2026-07-17,fulltime,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sociologia
15,in-3e25a6fcc1a564c2,indeed,https://pe.indeed.com/viewjob?jk=3e25a6fcc1a564c2,http://pe.indeed.com/job/analista-de-responsabilidad-social-empresarial-sector-energ%C3%ADa-3e25a6fcc1a564c2,Analista de Responsabilidad Social Empresarial - Sector Energía,Alupar,"Lima, LIM, PE",2026-07-17,fulltime,NaN,...,201 to 500,$100M to $500M (USD),NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sociologia
16,in-a484976dbb7b233c,indeed,https://pe.indeed.com/viewjob?jk=a484976dbb7b233c,http://pe.indeed.com/job/licenciado-sociologo-a484976dbb7b233c,LICENCIADO SOCIOLOGO,CONSORCIO SUPERVISOR HUAMACHUCO,"San Luis, LIM, PE",2026-07-15,fulltime,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sociologia
17,in-75c8e5790321547e,indeed,https://pe.indeed.com/viewjob?jk=75c8e5790321547e,http://pe.indeed.com/job/lic-en-sociologia-yo-antropologia-75c8e5790321547e,LIC. EN SOCIOLOGIA Y/O ANTROPOLOGIA,DON EDUARDO HJ SAC,"Aguas Verdes, TUM, PE",2026-07-15,"temporary, fulltime",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sociologia
18,in-52af1c7df8a8c6d0,indeed,https://pe.indeed.com/viewjob?jk=52af1c7df8a8c6d0,http://pe.indeed.com/job/especialista-en-criminologia-52af1c7df8a8c6d0,Especialista en Criminologia,PROYECTA INGENIEROS CIVILES S.A.C,"Lima, LIM, PE",2026-07-14,fulltime,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sociologia
19,in-cfbe1a6c33c7c0a2,indeed,https://pe.indeed.com/viewjob?jk=cfbe1a6c33c7c0a2,https://ocaglobal.teamtailor.com/jobs/8062347-profesional-especialista-en-rrcc-relaciones-comunitarias,Profesional Especialista en RRCC (Relaciones Comunitarias),OCA Global,"Alan Gabriel, LLI, PE",2026-07-14,NaN,NaN,...,"5,001 to 10,000",$100M to $500M (USD),NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sociologia
20,in-11979d1d67a9692b,indeed,https://pe.indeed.com/viewjob?jk=11979d1d67a9692b,http://pe.indeed.com/job/procesador-de-datos-senior-11979d1d67a9692b,Procesador de Datos Senior,CLÍNICA DE LIMA S.A.C.,"Arequipa, ARE, PE",2026-07-14,fulltime,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sociologia
21,in-64af094f59c8adc4,indeed,https://pe.indeed.com/viewjob?jk=64af094f59c8adc4,http://pe.indeed.com/job/convocatoria-docente-responsabilidad-social-y-relaciones-comunitarias-en-miner%C3%ADa-64af094f59c8adc4,CONVOCATORIA DOCENTE Responsabilidad Social y Relaciones Comunitarias en Minería,ELEVATE PERÚ,"Remote, PE",2026-07-13,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sociologia
22,in-6c4cdc75867c7b43,indeed,https://pe.indeed.com/viewjob?jk=6c4cdc75867c7b43,https://acciona.wd3.myworkdayjobs.com/en-US/ACCIONA_Employment_Channel/job/Lima/GESTOR-A--SOCIAL_20099327,GESTOR(A) SOCIAL,Acciona,"Lima, LIM, PE",2026-07-13,NaN,NaN,...,"10,000+",more than $10B (USD),NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sociologia
23,in-b9241fce1ef6a239,indeed,https://pe.indeed.com/viewjob?jk=b9241fce1ef6a239,https://acciona.wd3.myworkdayjobs.com/en-US/ACCIONA_Employment_Channel/job/Lima/GESTOR-A--SOCIAL_20099329,GESTOR(A) SOCIAL,Acciona,"Lima, LIM, PE",2026-07-13,NaN,NaN,...,"10,000+",more than $10B (USD),NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sociologia
24,in-8bbfe23eb374417a,indeed,https://pe.indeed.com/viewjob?jk=8bbfe23eb374417a,http://pe.indeed.com/job/consultor-de-tesis-y-art%C3%ADculos-cient%C3%ADficos-freelancer-8bbfe23eb374417a,CONSULTOR DE TESIS Y ARTÍCULOS CIENTÍFICOS - FREELANCER,ECONODATA SOLUCIONES PERU,"Remote, PE",2026-07-13,NaN,NaN,...,11 to 50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sociologia
25,in-69cee65da9780260,indeed,https://pe.indeed.com/viewjob?jk=69cee65da9780260,https://credicorp-capital.hirehive.com/design-lead-lima-JAmnUI?source=Indeed,Design Lead,CREDICORP CAPITAL,"Lima, LIM, PE",2026-07-10,fulltime,NaN,...,"501 to 1,000",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sociologia
26,in-ae19cf43b9e8ec11,indeed,https://pe.indeed.com/viewjob?jk=ae19cf43b9e8ec11,http://pe.indeed.com/job/relacionista-comunitario-ae19cf43b9e8ec11,Relacionista Comunitario,XLM SAC,"San Isidro, LIM, PE",2026-07-09,fulltime,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sociologia
27,in-0db189dc6bf97b2f,indeed,https://pe.indeed.com/viewjob?jk=0db189dc6bf97b2f,http://pe.indeed.com/job/trabajo-para-universitarios-part-time-0db189dc6bf97b2f,TRABAJO PARA UNIVERSITARIOS- PART TIME,GAMT,"Arequipa, ARE, PE",2026-07-08,"parttime, internship",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sociologia
28,in-8eafa44f318510a9,indeed,https://pe.indeed.com/viewjob?jk=8eafa44f318510a9,http://pe.indeed.com/job/especialista-en-criminolog%C3%ADa-o-gesti%C3%B3n-penitenciaria-8eafa44f318510a9,Especialista en Criminología o Gestión Penitenciaria,PROYECTA INGENIEROS CIVILES S.A.C,"Lima, LIM, PE",2026-07-03,fulltime,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sociologia
29,in-89871c74a3959e5a,indeed,https://pe.indeed.com/viewjob?jk=89871c74a3959e5a,http://pe.indeed.com/job/coordinadora-de-fundaci%C3%B3n-89871c74a3959e5a,Coordinadora de Fundación,WE EDUCACIÓN EJECUTIVA,"San Isidro, LIM, PE",2026-07-03,fulltime,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sociologia
30,in-bcb6c924fb167af4,indeed,https://pe.indeed.com/viewjob?jk=bcb6c924fb167af4,http://pe.indeed.com/job/investigador-redactor-junior-part-time-bcb6c924fb167af4,INVESTIGADOR REDACTOR JUNIOR- PART TIME,GAMT,"Arequipa, ARE, PE",2026-07-03,parttime,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sociologia
31,in-da83e709ba8ed6e9,indeed,https://pe.indeed.com/viewjob?jk=da83e709ba8ed6e9,http://pe.indeed.com/job/gestor-social-da83e709ba8ed6e9,Gestor Social,CORPORACION SANTAGUSTINA E.I.R.L,"Cajamarca, CAJ, PE",2026-07-02,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sociologia
32,in-d30e12a82fef6d75,indeed,https://pe.indeed.com/viewjob?jk=d30e12a82fef6d75,https://www.abrilhr.pe/api/v1/empresa/Alpayana/puesto/Supervisor-de-Comunidades-%7C-UM-Yauricocha-23550,Supervisor de Comunidades | UM Yauricocha,Alpayana,"Lima, LIM, PE",2026-06-24,fulltime,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sociologia
33,li-4446152370,linkedin,https://www.linkedin.com/jobs/view/4446152370,NaN,"Analista de Relaciones Gubernamentales, Perú",International Justice Mission,"Lima, Peru",2026-07-27,fulltime,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sociologia
34,li-4445370394,linkedin,https://www.linkedin.com/jobs/view/4445370394,NaN,Jefe de Crédito Grupal / Agencia Yurimaguas / Comisiones Ilimatadas,Compartamos Banco Perú,"Yurimaguas, Loreto, Peru",2026-07-26,fulltime,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sociologia
35,li-4427515092,linkedin,https://www.linkedin.com/jobs/view/4427515092,NaN,Analista de Proyectos de Inversión Pública con Enfoque Pedagógico (Ancash),Gilat Perú,"San Isidro, Peru",2026-07-25,fulltime,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sociologia
36,li-4445335399,linkedin,https://www.linkedin.com/jobs/view/4445335399,NaN,Asesor(a) en Formación de Crédito Grupal / Comisión Ilimitada / Agencias VMT y JOSÉ GÁLVEZ,Compartamos Banco Perú,"Villa María del Triunfo, Peru",2026-07-25,fulltime,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sociologia
37,li-4441846420,linkedin,https://www.linkedin.com/jobs/view/4441846420,NaN,ENCUESTADORES,Life Project´s - ONG,"Tarapoto, San Martín, Peru",2026-07-24,fulltime,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sociologia
38,li-4445233710,linkedin,https://www.linkedin.com/jobs/view/4445233710,NaN,Especialista Social Intermedio - Minería,WSP en Perú,"Lima, Peru",2026-07-24,fulltime,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sociologia
39,li-4444474407,linkedin,https://www.linkedin.com/jobs/view/4444474407,NaN,Gestor(a) Social,Minera Las Bambas,"Apurímac, Peru",2026-07-23,fulltime,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sociologia
40,li-4426563692,linkedin,https://www.linkedin.com/jobs/view/4426563692,NaN,Especialista de Relaciones Laborales,Gallagher,"Lima, Peru",2026-07-23,fulltime,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sociologia
41,li-4444238630,linkedin,https://www.linkedin.com/jobs/view/4444238630,NaN,Asesor Ventas de Campo ( Sueldo basico + planilla completa desde el 1er día),Compartamos Banco Perú,"Paucarpata, Arequipa, Peru",2026-07-23,fulltime,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sociologia
42,li-4444439713,linkedin,https://www.linkedin.com/jobs/view/4444439713,NaN,Promotor de Créditos / Zona de Puno,Compartamos Banco Perú,"Puno, Puno, Peru",2026-07-23,fulltime,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sociologia
43,li-4442947431,linkedin,https://www.linkedin.com/jobs/view/4442947431,NaN,Asistente Social Comunitario - Tacna,Aldesa,"Tacna, Tacna, Peru",2026-07-22,fulltime,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sociologia
44,li-4442932871,linkedin,https://www.linkedin.com/jobs/view/4442932871,NaN,Asistente Social Comunitario - Moquegua,Aldesa,"Moquegua, Moquegua, Peru",2026-07-22,fulltime,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sociologia
45,li-4441056546,linkedin,https://www.linkedin.com/jobs/view/4441056546,NaN,Coordinador(a) de Gestion Social,Manpower Perú,"Lima, Peru",2026-07-22,fulltime,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sociologia
46,li-4444206374,linkedin,https://www.linkedin.com/jobs/view/4444206374,NaN,Coordinador/a Social,ENGIE Perú,"Aguaytía, Ucayali, Peru",2026-07-22,temporary,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sociologia
47,li-4443948012,linkedin,https://www.linkedin.com/jobs/view/4443948012,NaN,Analista de sostenibilidad,Camposol S. A.,"Chao, La Libertad, Peru",2026-07-22,fulltime,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sociologia
48,li-4441068643,linkedin,https://www.linkedin.com/jobs/view/4441068643,NaN,Key Distributor Advisor - Rubro Lubricantes.,Manpower Perú,"Lima, Peru",2026-07-22,fulltime,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sociologia
49,li-4443709546,linkedin,https://www.linkedin.com/jobs/view/4443709546,NaN,(Agencia Trujillo Norte ) Asesor Negocios Crédito Grupal / Trabajo de Ventas en Campo,Compartamos Banco Perú,"Trujillo, La Libertad, Peru",2026-07-22,fulltime,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sociologia